name: Ping Supabase to Prevent Pausing

on:
  schedule:
    - cron: '5 14 * * 0' # Runs at 9:00 AM every Monday and Thursday

jobs:
  ping:
    runs-on: ubuntu-latest
    steps:
      - name: Ping server
        run: curl https://internal.taebforassembly.com/view/greeting
